### PR TITLE
166-feat: implement updating token

### LINKED ISSUE #166: Implement updating token when it expires
## Description

Right now, when the access token expires, the app does not update it. Because of this, API requests can fail and the user may be logged out by mistake.
It's cruccial to add a way to check if the token is expired and refresh it using the refresh token.

## Definition of Done

- [x] The app sees when the token is expired

- [x] If the token is expired, the app sends a request to get a new token

 - [x] If the new token is received, the app tries the request again

 - [x] If the refresh fails (for example, the refresh token is also expired) the user is logged out

### PR DESCRIPTION
**Pull request by alexspearsi**
## Description

Right now, when the access token expires, the app does not update it. Because of this, API requests can fail and the user may be logged out by mistake.
It's cruccial to add a way to check if the token is expired and refresh it using the refresh token.

## Definition of Done

- [x] The app sees when the token is expired

- [x] If the token is expired, the app sends a request to get a new token

 - [x] If the new token is received, the app tries the request again

 - [x] If the refresh fails (for example, the refresh token is also expired) the user is logged out
 
 ## Notes
 
 To check whether a refresh token works correctly you need to change the expires_at to 5 or other value
 
Скриншот 10-06-2025 230004

### CODE REVIEW

File: src/app/auth-service.ts [hunk 1]
```diff
@@ -1,12 +1,19 @@
...
+import { appState } from './app-state';
+import { AUTH_URL, CLIENT_ID, CLIENT_SECRET } from './constants';
 import { getAnonymousToken } from './ecommerce/get-anonymous-token';
 import { getAuthToken } from './ecommerce/get-auth-token';
 
 const TOKEN_KEY = 'auth_token';
 const IS_ANONYMOUS_KEY = 'is_anonymous';
+const REFRESH_TOKEN_KEY = 'refresh_token';
+const EXPIRES_AT_KEY = 'expires_at';
+const ONE_SECOND = 1000;
```
Comment (Tanya-Gro) [inline src/app/auth-service.ts]: Alex by "convention" constants are stored in shared/constants.ts. Put them there please, for consistency

File: src/shared/ui-config/button.ts [hunk 2]
```diff
@@ -53,7 +53,7 @@ export const BUTTONS_CONFIG: Button = {
             response.message === SERVER_ERROR_MESSAGES.CUSTOMER_NOT_FOUND
               ? SERVER_ERROR_MESSAGES.WRONG_CREDENTIALS
               : response.message;
-
+          console.log(message);
           createPopupMessage(message, false);
```
Comment (Tanya-Gro) [inline src/shared/ui-config/button.ts:56]: let's remove this log from the release

**Review by Tanya-Gro — COMMENTED** [review]
Great Alex!

**Review by koonukaame — APPROVED** [review]

**Comment by Tanya-Gro** [comment]
Alex, please rename the PR

File: src/shared/ui-config/button.ts (hunk 2 above)
Comment (alexspearsi) [reply src/shared/ui-config/button.ts:56]: Done

File: src/app/auth-service.ts (hunk 1 above)
Comment (alexspearsi) [reply src/app/auth-service.ts]: Done

**Review by Tanya-Gro — APPROVED** [review]
