### PR TITLE
159-feat: add actions to the add to cart button

### LINKED ISSUE #159: Add actions to the "Add to Cart" button
## Description

If the product is not already in the user's shopping cart, provide an "Add to Cart" button that adds the product with the selected options to their cart.
If the product is already in the user's shopping cart, allow users to remove a product directly from the product page if it is already in their shopping cart.

## Definition of done

- [ ] The application checks whether a product is already in the user's shopping cart before adding it.
- [ ] If the product is not already in the shopping cart, the "Add to Cart" button is active and can add the product to the cart.
- [ ] If the product is already in the shopping cart, the "Add to Cart" button is inactive or provides a relevant notice.
- [ ] The application correctly identifies whether a product is already in the user's shopping cart when viewing the product page.
- [ ] If the product is already in the shopping cart, a "Remove from Cart" button is visible and active on the product page.
- [ ] Clicking the "Remove from Cart" button triggers an API call to remove the corresponding product from the user's shopping cart.
- [ ] After successful removal, the user receives a confirmation message or visual cue.
- [ ] The application handles API errors gracefully, showing appropriate error messages if the removal operation fails.

### Notes
Consider implementing a universal "Add to Cart" button to work correctly on the catalog page and product page

### PR DESCRIPTION
**Pull request by Tanya-Gro**
## Description

Product page:
If the product is not yet in the cart, the user presses the "Add to cart" button, adding the product with the selected parameters to the cart. Then the button is inactive until the product is in the cart.
If the product is already in the cart, the user can delete the product directly from the product page. Then the button is inactive. It is activated after the product is returned to the cart.
Product page:
If the product is not yet in the cart, the user can send the product to the cart by pressing the "Add to cart" button. Then the "Add to cart" button is inactive.

## Definition of done
- [x] The application checks whether a product is already in the user's shopping cart before adding it.
- [x] If the product is not already in the shopping cart, the "Add to Cart" button is active and can add the product to the cart.
- [x] If the product is already in the shopping cart, the "Add to Cart" button is inactive or provides a relevant notice.
- [x] The application correctly identifies whether a product is already in the user's shopping cart when viewing the product page.
- [x] If the product is already in the shopping cart, a "Remove from Cart" button is visible and active on the product page.
- [x] Clicking the "Remove from Cart" button triggers an API call to remove the corresponding product from the user's shopping cart.
- [x] After successful removal, the user receives a confirmation message or visual cue.
- [x] The application handles API errors gracefully, showing appropriate error messages if the removal operation fails.

## Checklist

- [x] Follow project’s code style
- [ ] Add tests where applicable
- [x] No console errors/warnings

## Notes

Please check my PR after Alex merges his product removal fetches

### CODE REVIEW

File: src/components/catalog/card/card.ts [hunk 1]
```diff
@@ -1,16 +1,18 @@
...
+import { createDiv, createImg, createSpan } from '../../../utils/create-elements/create-tags';
+import { CARD } from '../../../pages/catalog/constants';
 import { calculateDiscount } from '../../../helpers/calculate-discount';
 import { createPriceComponent } from './price';
 import { Page } from '../../../app/constants';
 import { changePath } from '../../../app/router/handlers';
+import { addProductButton } from '../../../shared/components/add-to-cart-button';
 
-export function createProductCard(product: ProductProjection): HTMLDivElement {
+export function createProductCard(product: ProductProjection, existInCart: boolean): HTMLDivElement {
```
Comment (koonukaame) [inline src/components/catalog/card/card.ts:11]: Please either refactor this function to remove "Function 'createProductCard' has too many lines (55)" warning or change config

File: src/components/product/description.ts [hunk 2]
```diff
@@ -1,59 +1,59 @@
...
+import { addProductButton } from '../../shared/components/add-to-cart-button';
+import { removeProductButton } from '../../shared/components/remove-from-cart-button';
+import { getProductIdsExistInCart } from '../../helpers/get-ids-exist-in-cart';
 
-export function ProductDescription(productInfo: ProductInfo): HTMLElement {
-  const container = createDiv({ classes: PRODUCT_CLASSES.container });
-
-  createH2({
-    text: productInfo.productName,
+export async function ProductDescription(productInfo: ProductInfo): Promise<HTMLElement> {
```
Comment (koonukaame) [inline src/components/product/description.ts:11]: Please add whitespaces in this function because it's really hard to read in its current state.

File: src/shared/components/add-to-cart-button.ts [hunk 3]
```diff
@@ -0,0 +1,48 @@
+import { createButton } from '../../utils/create-elements/create-tags';
+import { addProductToCart } from '../../app/api/add-product-to-cart';
+import { BUTTON } from '../styles';
+import { getOrCreateCart } from '../../app/api/get-or-create-cart';
+import { isFetchError } from '../../utils/type-guards/is-fetch-error';
+import { createPopupMessage } from './popup';
+
+export function addProductButton(attributes: Record<string, string>): HTMLButtonElement {
```
Comment (koonukaame) [inline src/shared/components/add-to-cart-button.ts:4]: Why won't you move it in `ui-config/button.ts`?

File: src/shared/components/remove-from-cart-button.ts [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+import { getOrCreateCart } from '../../app/api/get-or-create-cart';
+import { removeProductFromCart } from '../../app/api/remove-product-from-cart';
+import { createPopupMessage } from './popup';
+
+const MESSAGES = {
+  success: 'Product removed from cart successfully',
+  error: 'Can`t remove product from cart',
+};
+
+export function removeProductButton(attributes: Record<string, string>): HTMLButtonElement {
```
Comment (koonukaame) [inline src/shared/components/remove-from-cart-button.ts:4]: Why won't you move it in `ui-config/button.ts`?

File: src/shared/components/add-to-cart-button.ts [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+        if (event.target instanceof HTMLButtonElement) {
+          addButtonClick(event.target);
+        }
+      },
+    },
+    text: 'Add to Cart',
+  });
+}
+
+const MESSAGES = {
```
Comment (koonukaame) [inline src/shared/components/add-to-cart-button.ts]: Maybe it would be a good idea to move it in `shared/constants.ts`? 

Also you can merge it with error messages from `src/shared/components/remove-from-cart-button.ts`

File: src/shared/components/remove-from-cart-button.ts [hunk 6]
```diff
@@ -0,0 +1,53 @@
+import { createButton } from '../../utils/create-elements/create-tags';
+import { BUTTON } from '../styles';
+import { isFetchError } from '../../utils/type-guards/is-fetch-error';
+import { getOrCreateCart } from '../../app/api/get-or-create-cart';
+import { removeProductFromCart } from '../../app/api/remove-product-from-cart';
+import { createPopupMessage } from './popup';
+
+const MESSAGES = {
```
Comment (koonukaame) [inline src/shared/components/remove-from-cart-button.ts]: Maybe it would be a good idea to move it in `shared/constants.ts`? 

Also you can merge it with error messages from `src/shared/components/add-to-cart-button.ts`

File: src/shared/components/remove-from-cart-button.ts [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+        if (event.target instanceof HTMLButtonElement) {
+          buttonClick(event.target);
+        }
+      },
+    },
+    text: 'Remove from Cart',
+  });
+}
+
+async function buttonClick(removeButton: HTMLButtonElement): Promise<void> {
```
Comment (koonukaame) [inline src/shared/components/remove-from-cart-button.ts]: Maybe it would be a good idea to move functionality from `shared/components` into `utils` or `helpers`?

File: src/shared/components/add-to-cart-button.ts [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+  success: 'Product added in cart successfully',
+  error: 'Can`t add product in cart',
+};
+
+async function addButtonClick(addButton: HTMLButtonElement): Promise<void> {
```
Comment (koonukaame) [inline src/shared/components/add-to-cart-button.ts]: Maybe it would be a good idea to move functionality from `shared/components` into `utils` or `helpers`?

File: src/components/product/layout.ts [hunk 9]
```diff
@@ -11,8 +11,9 @@ import { isFetchError } from '../../utils/type-guards/is-fetch-error';
 import { getProductById } from '../../app/api';
 
 export type ProductInfo = {
```
Comment (alexspearsi) [inline src/components/product/layout.ts:13]: this type doesn't have a `photo` property, but in line 56 it tries to get it 
```ts
const slider = ProductSlider(productInfo.photo);
```

File: src/utils/type-guards/is-fetch-error.ts [hunk 10]
```diff
@@ -1,7 +1,9 @@
 import type { AuthTokenError, FetchError } from '../../app/types';
-import type { Customer, ProductProjectionPagedQueryResponse } from '@commercetools/platform-sdk';
+import type { Cart, Customer, ProductProjectionPagedQueryResponse } from '@commercetools/platform-sdk';
 
-export function isFetchError(data: Customer | ProductProjectionPagedQueryResponse | FetchError): data is FetchError {
+export function isFetchError(
```
Comment (alexspearsi) [inline src/utils/type-guards/is-fetch-error.ts:4]: Good idea to create this function!

File: src/components/product/layout.ts (hunk 9 above)
Comment (Tanya-Gro) [reply src/components/product/layout.ts:13]: image

File: src/shared/components/add-to-cart-button.ts (hunk 5 above)
Comment (Tanya-Gro) [reply src/shared/components/add-to-cart-button.ts]: Are we supposed to have other components to add the product to the cart? I don't think so, that's why I left the messages next to the component. They definitely should have been moved to the beginning of the file, declared immediately after the imports, I missed that

File: src/shared/components/remove-from-cart-button.ts (hunk 7 above)
Comment (Tanya-Gro) [reply src/shared/components/remove-from-cart-button.ts]: I think it is more useful for the component callback to lie next to the component. It is not reused or exported, it is created to facilitate the readability of the component config.

File: src/shared/components/remove-from-cart-button.ts (hunk 4 above)
Comment (Tanya-Gro) [reply src/shared/components/remove-from-cart-button.ts:4]: done

File: src/shared/components/remove-from-cart-button.ts (hunk 6 above)
Comment (Tanya-Gro) [reply src/shared/components/remove-from-cart-button.ts]: done

File: src/components/catalog/card/card.ts (hunk 1 above)
Comment (Tanya-Gro) [reply src/components/catalog/card/card.ts:11]: done

File: src/components/product/description.ts (hunk 2 above)
Comment (Tanya-Gro) [reply src/components/product/description.ts:11]: done

File: src/shared/components/add-to-cart-button.ts (hunk 3 above)
Comment (Tanya-Gro) [reply src/shared/components/add-to-cart-button.ts:4]: done

File: src/shared/components/add-to-cart-button.ts (hunk 8 above)
Comment (Tanya-Gro) [reply src/shared/components/add-to-cart-button.ts]: done

**Review by alexspearsi — APPROVED** [review]
Well done Tanya!

File: src/shared/components/add-to-cart-button.ts (hunk 5 above)
Comment (koonukaame) [reply src/shared/components/add-to-cart-button.ts]: Didn't we decided to keep all constants in shared? Look there - `SERVER_ERROR_MESSAGES` for example is used only in `src/shared/ui-config/button.ts`, but it's declared in constants

File: src/shared/components/remove-from-cart-button.ts (hunk 7 above)
Comment (koonukaame) [reply src/shared/components/remove-from-cart-button.ts]: All of our callbacks are in utils - look at the `src/utils/validation`, it's callbacks mostly. Or `src/utils/query-handlers` - all of the files there are callbacks too. I think we should keep them outside of the `shared/components` for code consistency

File: src/shared/components/add-to-cart-button.ts (hunk 5 above)
Comment (Tanya-Gro) [reply src/shared/components/add-to-cart-button.ts]: Apparently I have a distorted understanding of the purpose of the shared folder. done

File: src/shared/components/remove-from-cart-button.ts (hunk 7 above)
Comment (Tanya-Gro) [reply src/shared/components/remove-from-cart-button.ts]: done

**Review by koonukaame — APPROVED** [review]
Good job!
